### ISSUE TITLE
quotes in CONDITIONS in mq are handled incorrectly

### ISSUE THREAD

**Issue by JorySchossau** [Hintzelab/MABE#114]
Consider the case of
CONDITIONS = MYVAR="Alice","Bob","Eve"
appears to be correctly translated to the terminal, but I suspect MABE does not know how to handle quotes, so it must instead be
CONDITIONS = MYVAR=Alice,Bob,Eve

**Comment by JorySchossau** [comment]
./MABE -p GLOBAL-myparam "a value" // this should work

**Comment by cgnitash** [comment]
On my terminal I need to escape the double quotes for MABE to read the string correctly.

**Comment by JorySchossau** [comment]
I'm not sure what you've done do your zsh config to get that behavior. Zsh works by default on a clean install.

**Comment by cgnitash** [comment]
Can you try setting initPop through the command line, and see if it works?

**Comment by JorySchossau** [comment]
Yes this works.

**Comment by cgnitash** [comment]
Ok, then it's something to do with my zsh config. So this resolves the issue, right?

**Comment by cgnitash** [comment]
Could you check if this problem is fixed? The way MABE read stuff from the terminal has changed, so it's possible this is resolved.

**Comment by JorySchossau** [comment]
It looks like the MABE side may be working nicely now as far as quotes go. Somehow `mq.py` is calling mabe in such a way that line 146 of `Parameters.cpp` is being triggered. I'm not sure how - I copy and paste the exact command mq is producing and mabe runs fine.

**Comment by cgnitash** [comment]
Yeah, that's weird. I tried the copy paste and that works fine.

I'll clean-up mq.py and then take a look at this.

**Comment by alackles** [comment]
Fixed by #239
