### ISSUE TITLE
Defaults in buildOptions.txt on development 

### ISSUE THREAD

**Issue by dkirkpatrick** [Hintzelab/MABE#123]
Is there a reason why cgp is the default brain type for buildOptions.txt?

**Comment by JorySchossau** [comment]
yup, it compiles quickly. This was such that the defaults will allow
moderately interesting behavior while allowing slower machines to even be
able to see quickly if their MABE setup can even compile.

**Comment by JorySchossau** [comment]
Let's try to use slack for questions between us.
