### ISSUE TITLE
Loading of Genomes

### ISSUE THREAD

**Issue by fischerdom** [Hintzelab/MABE#157]
Hey guys,

could it be that you deleted the feature to load already generated genomes? There is no usage of `Global::visualizePopulationFilePL` anymore 😢 

Cheers 
Dom

**Comment by cgnitash** [comment]
The Global::visualizePopulationFilePL Parameter has been deprecated. To load Genomes, you have to use the Global::initPopPL option. If you run mabe with -l a .plf file will be generated, which has examples of how to load Genomes.

**Comment by fischerdom** [comment]
Cool. Thank you very much 👍
