### ISSUE TITLE
Default Archivist Max org fails with score = 0

### ISSUE THREAD

**Issue by cliff-bohm** [Hintzelab/MABE#183]
I think it's because of this:
http://en.cppreference.com/w/cpp/types/numeric_limits/min

in particular:
"For floating-point types with denormalization, min returns the minimum positive normalized value. Note that this behavior may be unexpected, especially when compared to the behavior of min for integral types. To find the value that has no values less than it, use numeric_limits::lowest."

**Comment by cgnitash** [comment]
I'm not sure I understand the reasoning entirely of why it's needed. The footnote 190) in N4659:21.3.4.1 says "lowest() is necessary because not all floating-point representations have a smallest (most negative) value that is the negative of the largest (most positive) finite value."
