### ISSUE TITLE
MacOSX Compile Failure - isnan is not supported

### ISSUE THREAD

**Issue by JorySchossau** [Hintzelab/MABE#185]
The isnan function is not portable, and is currently being used in Xor World.

**Comment by JorySchossau** [comment]
How did Arend compile this??? (he wrote it)

**Comment by JorySchossau** [comment]
Okay, I discovered GCC 7.3.0 for mac (via homebrew - the most popular method) does not support isnan.

**Comment by JorySchossau** [comment]
@cgnitash will be so vindicated: adding std:: to isnan and isinf fixes the problem because of conflicts with math and cmath.

**Comment by cgnitash** [comment]
I am vindicated :) So I take it #186 resolves this issue.
