### ISSUE TITLE
gitversion.h does not exist by default

### ISSUE THREAD

**Issue by JorySchossau** [Hintzelab/MABE#188]
project should build without mbuld.py, out of the box, but right now we require mbuild.py to generate gitversion.h as it does not exist by default.

**Comment by cgnitash** [comment]
I'm not sure what you mean, "should build without mbuild.py"? I thought we were requiring it (as far as MABE guidelines go).

**Comment by cgnitash** [comment]
The gitversion feature doesn't work for me. Even with a fresh build via mbuild.py, the extern gitversion is not visible in Parameters.cpp

**Comment by JorySchossau** [comment]
- What error do you get?
- Is gitversion.h generated correctly with a git hash as a const char string?

**Comment by JorySchossau** [comment]
You're right, that it doesn't make sense to include because modules.h isn't there either. Moving the discussion about the error to slack.
