### ISSUE TITLE
Typo on the Wiki

### ISSUE THREAD

**Issue by mmore500** [Hintzelab/MABE#203]
In this figure (https://github.com/Hintzelab/MABE/wiki/images/MABE_Overview.png), "Organisam" should be spelled "Organism."

![https://github.com/Hintzelab/MABE/wiki/images/MABE_Overview.png](https://github.com/Hintzelab/MABE/wiki/images/MABE_Overview.png)

**Comment by cgnitash** [comment]
Nice catch, thanks. Fixed.
