### ISSUE TITLE
.plf file not loading correctly 

### ISSUE THREAD

**Issue by dkirkpatrick** [Hintzelab/MABE#242]
See image: files exist but "does not match any files" error 
![image](https://user-images.githubusercontent.com/7990861/42044571-5e90ac4c-7ac7-11e8-8a15-059363540a67.png)

**Comment by cgnitash** [comment]
I might know what's causing this. Try ending your wildcard search with *.csv, instead of just *

**Comment by dkirkpatrick** [comment]
Same issue: 

Creating population from plf0Test.plf
 warning: C0__useNA_1__wchNC_0__altNC_3__invNC_0/*/LOD*.csv does not match any files

**Comment by dkirkpatrick** [comment]
Issue is with Symlinks, see new issue #246
