### ISSUE TITLE
Population Loading doesn't follow Symlinks 

### ISSUE THREAD

**Issue by dkirkpatrick** [Hintzelab/MABE#246]
As the title says, pop loading does not process symlinks (discovered while working on #242 )

By default mq uses symlinks to store data on scratch on the HPCC. As a result, running analysis on the HPCC is not easily done in the current setup, which I think we should fix

**Comment by dkirkpatrick** [comment]
My proposal would be to follow a bounded number of subdirectories in the symlink (i.e. follow the symlink + 1 subdirectory level)

**Comment by JorySchossau** [comment]
Just adding history: Originally, this was a zupply problem and we fixed it by fixing the call to get_current_dir() to handle symlinks correctly: https://github.com/zhreshold/zupply/commit/7c1f1bf46fc951c4b0d4155b857ed918cd2589cc
