### ISSUE TITLE
Population Loading Fails on Windows

### ISSUE THREAD

**Issue by dkirkpatrick** [Hintzelab/MABE#247]
Population Loading fails on Windows.  May be related to #242 and wildcard expansion or the backslash versus forwardslash conventions 

![image](https://user-images.githubusercontent.com/7990861/42344837-8bb2fdfc-806b-11e8-8b8d-4d2882e6949a.png)

**Comment by cgnitash** [comment]
Try changing the regex to ignore both kinds of slashes.
