### ISSUE TITLE
In Sep/Oct move to experimental/filesystem

### ISSUE THREAD

**Issue by JorySchossau** [Hintzelab/MABE#251]
Resolves #246 and #247, maybe.

In September/October timeframe, the new Xcode 10 ships with the new OSX 10.14 "mojave" and will have experimental/filesystem support. We have yet to determine if all compilers support the <experimental/filesystem> and -stdc++fs build workflow.

**Comment by cgnitash** [comment]
Sadly, it seems that the version of clang shipping with Xcode 10 is not c++17 compliant. 
I would recommend waiting till we move to c++17 (possibly in a few months), and then we can directly use <filesystem>. We can figure out how to handle mac users who can't install modern compilers themselves.
