### ISSUE TITLE
MABE acronym

### ISSUE THREAD

**Issue by JorySchossau** [Hintzelab/MABE#280]
The proposal that came up is to make it: Modular Agent Based Evolution platform.

**Comment by cliff-bohm** [comment]
MABEP?

**Comment by cliff-bohm** [comment]
I don't really care. From a historic perspective, the name was Modular Agent-Based Evolver.

i.e. MABE evolves stuff... it is an evolver.

**Comment by JorySchossau** [comment]
Yeah, we've been using "framework" and "platform" a lot more, so it's just been an "evolution" of usage.

**Comment by JorySchossau** [comment]
Fixed in wiki commit.
