### ISSUE TITLE
OPTIMIZER_SIMPLE options are not recognized

### ISSUE THREAD

**Issue by trougnouf** [Hintzelab/MABE#40]
Running MABE with OPTIMIZER_SIMPLE parameters such as `MABE -p OPTIMIZER_SIMPLE-numberParents 2` returns
`  ERROR :: while reading command line found "OPTIMIZER_SIMPLE-numberParents.
      But "OPTIMIZER_SIMPLE-numberParents" is not a registered parameter!
  Exiting.
`

**Comment by JorySchossau** [comment]
Hi, welcome and thank you for reporting a problem. Please let me know which branch you pulled from (either development or master) and which commit you have if on development if you happen to know it. I cannot replicate this problem on the latest development or the last stable master release. Make sure to refresh your build by running MBuild again, and ensuring you do indeed have OPTIMIZER_SIMPLE enabled in the resulting settings.cfg file after running MABE -s.

**Comment by JorySchossau** [comment]
Please read the Wiki if you haven't already then join the help and development chat room on gitter if you could use more immediate assistance: https://gitter.im/hintze-lab/MABE

**Comment by trougnouf** [comment]
Thank you for your quick response. I wasn't aware of the development branch and I must have inadvertently built it because the master branch builds with the "GA" optimizer instead. Sorry for the inconvenience.
