### ISSUE TITLE
Duplicate buildOptions.txt

### ISSUE THREAD

**Issue by trougnouf** [Hintzelab/MABE#44]
The file buildOptions.txt is present in both the root directory, and PythonTools.
I believe that PythonTools/buildOptions.txt should be removed, as trying to use it results in an error and having both files present induces confusion.

terminal output: https://pastebin.com/U5Mp4VjV , using the development branch.

**Comment by JorySchossau** [comment]
This is the result of wonderful historical contingency :) The interim solution will be to delete the PythonTools/buildOptions.txt until buildOptions.txt can be automatically generated from MBuild.

**Comment by JorySchossau** [comment]
Thanks for reporting!

**Comment by trougnouf** [comment]
Thank you!
