### ISSUE TITLE
Population Loader Bad Path on File on HPCC

### ISSUE THREAD

**Issue by dkirkpatrick** [Hintzelab/MABE#63]
I have a set of files that runs fine locally: 

//BEGIN EXCERPT//
Loading from File population_loader.cfg

Loading 0 Random organisms
Loading 0 Default organisms
From file snapshot_organisms_200000.csv
  Loading organisms with IDs : 50000001 50000002 
//END EXCERPT//

However, when the same program is run on the HPCC (submitted with MQ.qsub), it breaks: 

//BEGIN EXCERPT//
Loading from File population_loader.cfg
 error: unable to load../../../ls15/scratch/users/kirkpa48/C1_105__FDPTRN_AlternatingCorners__WLDRST_1_105__2017_11_27_22_25_11/snapshot_organisms_200000.csv
//END EXCERPT//

The correct file is where it is supposed to be: 

//BEGIN EXCERPT//
[kirkpa48@dev-intel16 C1_105__FDPTRN_AlternatingCorners__WLDRST_1_105__2017_11_27_22_25_11]$ ls
C1_105__FDPTRN_AlternatingCorners__WLDRST_1.out  MQ.qsub                settings_organism.cfg
C1__FDPTRN_AlternatingCorners__WLDRST_1          population_loader.cfg  settings_world.cfg
MABE                                             settings.cfg           snapshot_organisms_200000.csv
//END EXCERPT//

but something else seems to be going on in the filesystem.  Please advise

**Comment by JorySchossau** [comment]
Try adding a './' in front of the path, like ./../../../ls15/scratch/users/kirkpa48/C1_105__FDPTRN_AlternatingCorners__WLDRST_1_105__2017_11_27_22_25_11/snapshot_organisms_200000.csv
If no luck, then try putting the file in the same level or lower (as a subdir) of the dir where MABE is being run. These guesses are based on the bits of source I read while putting the new lib in.
Check w/ Nitash on slack if it is a requirement that loaded csv files be at the same dir level or lower as MABE.

**Comment by dkirkpatrick** [comment]
The file (see ls output) is in the same directory and the file should be locally pathed (i.e. the source is MASTER = 'snapshot_organisms_200000.csv').  I'm not sure where the ../../../ls15/scratch/users/kirkpa48/C1_105__FDPTRN_AlternatingCorners__WLDRST_1_105__2017_11_27_22_25_11 portion is coming from

**Comment by JorySchossau** [comment]
Offlining to slack conversation.

On Tue, Nov 28, 2017 at 11:07 AM, Doug Kirkpatrick <notifications@github.com
