### ISSUE TITLE
Loading Files could be more user friendly 

### ISSUE THREAD

**Issue by dkirkpatrick** [Hintzelab/MABE#85]
Filenames for loading pop files seem to have to have a '_organisms.csv' ending; it seems like users should be able to set any file names they so choose

Also, there may be a recursive file issue for .plf files

**Comment by cgnitash** [comment]
Yeah, the filename needs to end in '_organisms.csv' or '_organisms_#.csv'. This is intentional, otherwise searching using a wild card means _every_ file needs to be opened and read in case it could contain population data.

What issue with .plf specifically?

**Comment by JorySchossau** [comment]
The only issues are a lack of documentation at this point. It's all good!
