### ISSUE TITLE
negative numbers cannot be passed on the CLI to MABE

### ISSUE THREAD

**Issue by JorySchossau** [Hintzelab/MABE#97]
The following command is not allowed by MABE while it should be.
`./MABE -p GLOBAL-randomSeed -1`

**Comment by cgnitash** [comment]
Yeah, this needs to be fixed. What behaviour should randomSeed -1 have?

**Comment by JorySchossau** [comment]
I suspect the behavior should be just like that of the config file "randomSeed = -1" behavior which does the right thing in main.cpp to provide a random seed based on operating system.
Do a hotfix based on main, and then make a pull request to both main and development.

**Comment by cgnitash** [comment]
You mean master and development, correct?

**Comment by JorySchossau** [comment]
Oop, yes master and development.

**Comment by cgnitash** [comment]
I fixed it on development(oops), and then made a pull request to master. I can't seem to make multiple pull requests though. Did I misunderstand what you meant?

**Comment by cgnitash** [comment]
Ok, I made both pull requests. But I fixed it on development, so if that's a problem, I'll redo it.

**Comment by JorySchossau** [comment]
Should be okay since we had a release quite recently.
